# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
    - master
    - v3

pr:
  autoCancel: true
  batch: true
  branches:
    include:
    - master
    - v3

variables:
  TESTS_MULTIREGION: true
  MOCHA_TIMEOUT: 30000

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    node --version
    npm --version
    npm install
    npm run build
  displayName: 'npm install and build'

- script: | 
    npm pack
  displayName: 'npm pack'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **\*.js
      package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'package'
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'

- script: |
    npm run ci
  displayName: 'npm test'